import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      "build/**",
      ".react-router/**",
      ".wrangler/**",
      "src/generated/**",
      "public/**",
      // Plain Node CLI script (wrangler d1 execute wrapper), not part of the
      // app bundle — no Workers/browser globals config applies to it.
      "scripts/**",
      // Generated by `wrangler types` (npm run cf-typegen) — huge, not ours to lint.
      "worker-configuration.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs["recommended-latest"],
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
);
